name: Test, Upload artifact and Deploy to Heroku

on: push

jobs:
  test:
    name: run unit tests on java ${{ matrix.java }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [17]
    steps:
      - uses: actions/checkout@master
      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - run: mvn -f pom.xml clean test
      
  release:
    name: Build, Package and upload .jar artifact
    runs-on: ubuntu-latest
    needs: test
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17
        
    - name: Build and package project
      run: mvn -f pom.xml clean package
    
    - name: Show contenst of the current working directory
      run: ls -la
      
    - name: Show contents of target directory
      run: ls -la target
    
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}} #Must be unique in Heroku
          heroku_email: ${{secrets.HEROKU_EMAIL}}

      
